baseURL = 'https://run0v.ru/'
languageCode = 'ru-RU'
title = 'run0v blog'
uglyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmptyBundles = true
timeZone = 'Europe/Moscow'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[params]
    mainSections = ["test"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Test"
    url = "/test/"
    weight = 2