baseURL = 'https://run0v.ru/'
languageCode = 'ru-RU'
title = 'run0v blog'
uglyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmptyBundles = true
timeZone = 'Europe/Moscow'
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true

[params]
    mainSections = ["notes"]
    
[[menu.main]]
    
    name = "Записки"
    
    url = "/notes/"
    
    weight = 1
    

    
[[menu.main_sidebar]]
    
    name = "Обо мне"
    
    url = "/about/"
    
    weight = 1
    

    
[[menu.main_sidebar]]
    
    name = "Проекты"
    
    url = "/projects/"
    
    weight = 2
    