baseURL = 'https://run0v.ru/'
languageCode = 'ru-RU'
title = 'run0v blog'
uglyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmptyBundles = true
timeZone = 'Europe/Moscow'
disableHugoGeneratorInject = true
enableRobotsTXT = true